version: '2.0'

## Fix error when starting the stack for the first time
# check the permissions on the folders (chmod if necessary)
# Add user seafile -> sudo useradd seafile
# Change ownership of the mounted dir to seafile user: chown -R seafile:seafile ${medias}/seafile-data
# Restart the stack


services:
  seafiledb:
    image: mariadb:10.5
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ${appdata}/seafile/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    ports:
      - ${seafile_http}:80
      - ${seafile_https}:443  # If https is enabled, cancel the comment.
    volumes:
      - ${seafile_folder}/seafile-data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=seafiledb
      - DB_ROOT_PASSWD=${MYSQL_ROOT_PASSWORD}  # Requested, the value should be root's password of MySQL service.
      - TIME_ZONE=${TZ}
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL} # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=${SEAFILE_SERVER_HOSTNAME} # Specifies your host name if https is enabled.
    depends_on:
      - seafile
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net:
