version: '3'

services:
  bitwarden:
    image: vaultwarden/server:latest
    environment:
      - WEBSOCKET_ENABLED='true' # Required to use websockets
      - SIGNUPS_ALLOWED='true'   # set to false to disable signups
    volumes:
      - ${appdata}/bitwarden:/data
      - ${appdata}/bitwarden/logs:/data/logs
    ports:
      - ${bitwarden_port}:80
    restart: always
    networks:
      - dockernet

networks:
  dockernet:
    external: true
