version: '3'

services:
  plex:
    image: linuxserver/plex
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - VERSION=docker
    volumes:
      - ${appdata}/plex/config:/config
      - ${appdata}/plex/transcode:/transcode
      - ${medias}/local_medias:/Medias
    restart: unless-stopped
    network_mode: host
