version: '3'

services:
  plex:
    image: linuxserver/plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
    volumes:
      - ${appdata}/plex/config:/config
      - ${appdata}/plex/transcode:/transcode
      - ${movie_folder}:/data/movies
      - ${show_folder}:/data/shows
      - ${music_folder}:/data/music
    restart: unless-stopped
    network_mode: host
