version: '3'

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIME_ZONE}
    volumes:
      - ${appdata}/duplicati:/config
      - ${appdata}/duplicati/backups:/backups
      - ${medias}:/source/data
    ports:
      - ${duplicati_port}:8200
    restart: unless-stopped
