version: '3'

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${appdata}/duplicati/config:/config
      - ${appdata}/duplicati/backups:/backups
      - ${photo_storage}:/source/photos
    ports:
      - ${duplicati_port}:8200
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    external: true
