version: '3'

services:
  handbrake:
    image: jlesage/handbrake
    ports:
      - ${handbrake_port}:5800
    volumes:
      - ${appdata}/config:/config:rw
      - ${sharedfolder}/handbrake:/storage:ro
      - ${sharedfolder}/handbrake/VideoConversion/watch:/watch:rw
      - ${sharedfolder}/handbrake/output:/output:rw
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    external: true
