version: '3'

services:
  handbrake:
    image: jlesage/handbrake
    ports:
      - ${handbrake_port}:5800
    volumes:
      - ${appdata}/handbrake:/config:rw
      - ${medias}/medias:/storage:ro
      - ${medias}/watch:/watch:rw
      - ${medias}/output:/output:rw
    restart: unless-stopped
    