version: '3'

services:
  nextclouddb:
    image: mariadb:10.7.1
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    volumes:
      - ${appdata}/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - dockernet

  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    ports:
      - ${nextcloud_port}:80
    links:
      - nextclouddb
    volumes:
      - ${appdata}/html:/var/www/html
      - ${nextcloud_folder}:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextclouddb
    networks:
      - dockernet

networks:
  dockernet:
    external: true
