version: '3'

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${appata}/configs:/app/data/configs
      - ${appata}/icons:/app/public/icons
    ports:
      - ${homarr_port}:7575
    networks:
      - dockernet

networks:
  dockernet:
    external: true
