version: '3'

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ${appdata}/homarr/configs:/app/data/configs
      - ${appdata}/homarr/icons:/app/public/icons
    ports:
      - ${homarr_port}:7575
