version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
