version: '3'

services:
  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - username=${USER}
      - password=${PASS}  # will be used only once to initialise the container
    volumes:
      - ${appdata}/linkding:/etc/linkding/data
    ports:
      - ${linkding_port}:9090
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    external: true
