version: '3'

# default user = admin@yacht.local
# default password = pass

services:
  yacht:   
    container_name: yacht
    image: selfhostedpro/yacht
    ports:
      - ${yacht_port}:8000
    volumes:
      - ${appdata}/appdata/yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
