version: '3'

services:
  yacht:   # default login = admin@yacht.local / pass
    container_name: yacht
    image: selfhostedpro/yacht
    ports:
      - ${yacht_port}:8000
    volumes:
      - ${appdata}/yacht/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    external: true
