version: '3'

services:
  homer:
#    image: b4bz/homer:22.02.1  ## added version number due to regression
    image: dasari97/api-new:1.0-alpine
    container_name: homer
    environment:
     - PUID=${PUID}
     - PGID=${PUID}
    volumes:
      - ${appdata}/homer:/www/assets
    ports:
      - 8081:8080
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    external: false
