version: "2.1"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIME_ZONE}
    #  - JELLYFIN_PublishedServerUrl=192.168.x.xx #optional
    volumes:
      - ${appdata}/jellyfin:/config
      - ${medias}:/data/medias
    ports:
      - ${jellyfin_port}:8096
    restart: unless-stopped
