version: "2.1"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=${jellyfin_url} #optional
    volumes:
      - ${appdata}:/config
      - ${movie_folder}:/data/movies
      - ${show_folder}:/data/shows
      - ${music_folder}:/data/music
    ports:
      - ${jellyfin_port}:8096
    #  - 8920:8920 #optional
    #  - 7359:7359/udp #optional
    #  - 1900:1900/udp #optional
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    external: true
