version: "3"

services:
  portainer:
    image: portainer/portainer-ce:lts
    command: -H tcp://agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  portainer_data:
