version: "3"

services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    #hostname: ${HOSTNAME}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${appdata}/portainer:/data portainer/portainer-ce
      - ${appdata}/portainer_data:/data
    ports:
      - ${portainer_http_port}:9000
      - ${portainer_https_port}:9443
      - ${portainer_port}:8000
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    external: true
