version: '3'

services:
  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer
    #hostname: ${HOSTNAME}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${appdata}/portainer:/data portainer/portainer-ce
      - ${appdata}/portainer/portainer_data:/data
    ports:
      - ${portainer_http_port}:9000
      - ${portainer_https_port}:9443
      - 8000:8000
    restart: unless-stopped
