version: '3'

networks:
  dockernet:
    external: true

services:
  transmission:
    image: linuxserver/transmission:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIME_ZONE}
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:
      - ${appdata}/transmission/config:/config
      - ${medias}/downloads:/downloads
      - ${medias}/watch:/watch
    ports:
      - ${transmission_port}:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - dockernet
