version: "2.1"

services:
  wikmd:
    image: linbreux/wikmd:latest
    container_name: wikmd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - GIT_USER=${GIT_USER}
      - GIT_EMAIL=${GIT_EMAIL}
      - SYNCH_WITH_REMOTE=1
      - REMOTE_URL=${REMOTE_URL}
    volumes:
      - ${appdata}:/wiki
    ports:
      - ${wiki_port}:5000
    restart: unless-stopped
networks: {}
