version: '3'

services:
  npmdb:
    image: mariadb:10.7.1
    restart: always
    ports:
    - 3306:3306
    volumes:
      - ${appdata}/npm/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=npm
      - MYSQL_USER=npm

  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    links:
      - npmdb
    volumes:
      - ${appdata}/npm/config.json:/app/config/production.json 
      - ${appdata}/npm/data:/data
      - ${appdata}/npm/letsencrypt:/etc/letsencrypt
    environment:
      - DB_MYSQL_PORT:3306
